### ISSUE TITLE
Chemical Oxidizer not accepting Vanilla Food Pantry salt.

### ISSUE THREAD

**Issue by Renari** [mekanica/mekanica#149]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
The chemical oxidizer doesn't accept vanilla food pantry salt to create brine.

#### Steps to reproduce:
1. Put vanilla food pantry salt in oxidizer.
2. Nothing happens.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2824
**Mekanica:** 1.1.1
**Other relevant version:** 4.3.0

![image](https://user-images.githubusercontent.com/1839179/55294707-4b6ab500-53d3-11e9-92b6-a1a58b73eaa1.png)

**Comment by Renari** [comment]
It appears this is also the case for salt blocks.

**Comment by pupnewfster** [comment]
My guess is that they are not registering their items/blocks to the ore dictionary when they register them and are doing it at some later stage. (If it works in main branch mekanism and just not in mekanica, that is because I moved recipe registration to happen during the recipe registry event. (Which is still after the registration of blocks and items), my guess is that they are registering to oredict during init or postinit.

Eventually at some point I plan on adding support for recipes via ore dict directly (would make it not care when an item was registered to the ore dict) instead of us looping over specific ore dictionary entries and then adding them but that is a ways off.

**Comment by Renari** [comment]
It seems this may be intentional:
https://github.com/Wabbit0101/mods_hoardercraft/issues/31
