### ISSUE TITLE
Version number breaks Netherending  Ores

### ISSUE THREAD

**Issue by Dannerick** [mekanica/mekanica#21]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Changing the version numbering breaks NetherendingOres as it requires a minimum version of 9.4.13. In software development, it is usually a bad idea to roll the version numbering backward. You should look at rolling the version number forward to 10.x instead.

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by trabpukcip** [comment]
I agree with moving the version forward.\
I have worked around the issue on the Netherending Ores end for the time being by removing the version check altogether in a hotfix now on curseforge. The version check was required when using the recipe api as it was broken due to a small bad bit of code. See here: https://github.com/aidancbrady/Mekanism/issues/5013

**Comment by dizzyd** [comment]
I'm going to close this, since there's a work around. At some point, we'll need to figure out a better way to attack the API.
