### ISSUE TITLE
Exception thrown when logistical sorter runs

### ISSUE THREAD

**Issue by temp1011** [mekanica/mekanica#65]
#### Issue description:
Error appears in log when logistical sorter used and sound doesn't play

#### Steps to reproduce:
1. put logistical sorter between two chests
2. add any itemstack to input chest and switch on auto mode
3. error appears (stack is still moved though)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2808
**Mekanism:** https://github.com/mekanica/mekanica/commit/b4251d2e3ddbef733fb814411267614da5db70a3

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://gist.github.com/temp1011/f57f531b67c83061b1833d87c897cde4

**Comment by temp1011** [comment]
This occured in dev/deobsfucated environment if that matters.

**Comment by dizzyd** [comment]
Hi @temp1011 - thanks for the PR, but the problem was that some Mekanica events were block events that were also one time events. We don't want them added to the sound map, so we can't just fix up the accessor. I adjusted the filter to catch them by name instead of category and all should be well. :)

**Comment by temp1011** [comment]
Glad we got tge right fix in the end :)
