### ISSUE TITLE
Disabling copper also disables salt generation

### ISSUE THREAD

**Issue by edenpc** [mekanica/mekanica#75]
#### Issue description:
After disabling Mekanica's copper generation and recreating the world, all visible salts blocks generated near water in the old world are now replaced by air in the new world.  

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2768
**Mekanism:** 1.12.2-1.0.0

**Comment by dizzyd** [comment]
When you say "recreated" the world, did you just create a new world with the same seed or something else?

**Comment by edenpc** [comment]
New world with the same seed.

**Comment by dizzyd** [comment]
Would you mind sharing the seed so I can check, please?

**Comment by edenpc** [comment]
So I've just explored the world a bit further and found some salt, so I guess I was wrong. Sorry for making an issue out of this. So maybe disabling copper slightly changed where salt was distributed?

Anyhow, the seed is -4991464139024885600

**Comment by pupnewfster** [comment]
Without looking at the code, I think I can explain why disabling copper is (probably) changing where salt is generated. IIRC most ores and the salt in mekanism use a random number to generate where it spawns. But if it would normally generate copper first, but doesn't because that is disabled, then when it passes the random number generator to the salt generation, it would have a different next random value.

**Comment by dizzyd** [comment]
Yes, the RNG is dependent on previous values - if one generator is disabled, it means the current seed for the next one will be different. @edenpc I'm going to close this issue, but if you find something else concerning, please let me know.
