### ISSUE TITLE
MekanismOres integrated into Mekanica

### ISSUE THREAD

**Issue by SacrificialFlame** [mekanica/mekanica#95]
**Describe the the feature you'd like**
A clear and concise description of what you want.
Away to have MekanismOres integrated into Mekanica, I asked the dev to add support for Mekanica and he would not add support 
**Describe alternatives you've considered**

**Additional context**
https://minecraft.curseforge.com/projects/mekanismores?gameCategorySlug=mc-mods&projectID=313340

**Comment by pupnewfster** [comment]
Sort of is mentioned here some https://github.com/mekanica/mekanica/issues/3

But a couple side notes:
1. Mekanica supports MekanismOres, tested it earlier today in fact to make sure I didn't break compat with addons when I was messing around with Recipe stuff some.
2. I do plan on at some point adding a way so that it can generate 5x ore processing for *any* ore.
